security:
    encoders:
        Societo\AuthenticationBundle\Entity\Account:
            algorithm:  sha1
            iterations: 5000
            encode_as_base64: false

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        societo_user_provider:
            id: societo.user.provider

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

        registration:
            pattern:  ^/registration.*
            security: false

        signup:
            pattern:  ^/signup.*
            security: false

        login:
            pattern:  ^/login$
            security: false

        public:
            pattern:  ^/public/.*
            security: false

        installer:
            pattern:  ^/install.*
            security: false

        main:
            provider: societo_user_provider
            form_login:
                check_path:                     /login_check
                login_path:                     /login
                failure_path:                   null
                always_use_default_target_path: false
                default_target_path:            /
                target_path_parameter:          _target_path
                use_referer:                    false
            remember_me:
                key:      aSecretKey
                lifetime: 2592000
                path:     /
                domain:   ~
            anonymous: ~
            logout: ~

    access_control:
        - { path: ^/admin*, roles: ROLE_ADMIN }
        - { path: ^/, roles: [IS_AUTHENTICATED_ANONYMOUSLY, ROLE_USER] }
#        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }
#        - { path: ^/_internal, roles: IS_AUTHENTICATED_ANONYMOUSLY, ip: 127.0.0.1 }
